name: dart_otp
description: dart_otp is a dart package to generate and verify one-time passwords.
version: 1.3.0
author: Gin <gin.lance.inside@hotmail.com>

homepage: https://github.com/BrunoMiguens/dart_otp

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  crypto: ^3.0.1
  base32: ^2.1.1

dev_dependencies:
  test: ^1.16.5
  test_coverage:
    git:
      url: https://github.com/Jjagg/test-coverage.git
      ref: 5a03fd76bb46db75885582aa3a7f70f0ba171378